/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICalltie, ICalltieInterface } from "../ICalltie";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newInfluencer",
        type: "address",
      },
    ],
    name: "changeInfluencer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newSubscriptionCost",
        type: "uint256",
      },
    ],
    name: "changeSubscriptionCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "subscriptionCALLTIE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICalltie__factory {
  static readonly abi = _abi;
  static createInterface(): ICalltieInterface {
    return new utils.Interface(_abi) as ICalltieInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICalltie {
    return new Contract(address, _abi, signerOrProvider) as ICalltie;
  }
}
